## 1. Import Libraries

In [2]:
import pandas as pd
import numpy as np 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from imblearn.over_sampling import SMOTE

## 2. Load Dataset

In [3]:
train_df=pd.read_csv("../data/raw/aps_failure_training_set.csv",skiprows=20,na_values="na")

In [4]:
df_preprocessed = train_df.copy()

## 3. Basic Dataset Information

In [5]:
df_preprocessed.shape

(60000, 171)

In [6]:
df_preprocessed.head()

  class  aa_000  ab_000        ac_000  ...    ee_008  ee_009  ef_000  eg_000
0   neg   76698     NaN  2.130706e+09  ...   73224.0     0.0     0.0     0.0
1   neg   33058     NaN  0.000000e+00  ...   97576.0  1500.0     0.0     0.0
2   neg   41040     NaN  2.280000e+02  ...   95128.0   514.0     0.0     0.0
3   neg      12     0.0  7.000000e+01  ...       0.0     0.0     4.0    32.0
4   neg   60874     NaN  1.368000e+03  ...  433954.0  1218.0     0.0     0.0

[5 rows x 171 columns]

In [7]:
df_preprocessed.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 171 entries, class to eg_000
dtypes: float64(169), int64(1), str(1)
memory usage: 78.3 MB

## 4. Check Missing Values

In [9]:
df_preprocessed.isnull().sum()

class         0
aa_000        0
ab_000    46329
ac_000     3335
ad_000    14861
          ...
ee_007      671
ee_008      671
ee_009      671
ef_000     2724
eg_000     2723
Length: 171, dtype: int64

In [10]:
df_preprocessed.isnull().sum().sort_values(ascending=False).head(20)

br_000    49264
bq_000    48722
bp_000    47740
bo_000    46333
ab_000    46329
cr_000    46329
bn_000    44009
bm_000    39549
bl_000    27277
bk_000    23034
ad_000    14861
cg_000    14861
ch_000    14861
cf_000    14861
co_000    14861
cx_000    13808
cz_000    13808
cy_000    13808
dc_000    13808
db_000    13808
dtype: int64

## Check Duplicated Rows

In [ ]:
df_preprocessed.duplicated().sum()

np.int64(0)

## Separate Features and Target

In [13]:
x=df_preprocessed.drop(columns=["class"])
y=df_preprocessed["class"]

In [14]:
y.value_counts()

class
neg    59000
pos     1000
Name: count, dtype: int64

## Label Encoding


The target contains two classes:

- `neg` → No APS failure
- `pos` → APS failure

We use LabelEncoder to convert them into numerical values.

In [15]:
le=LabelEncoder()
y=le.fit_transform(y)

In [ ]:
le.classes_

"""
neg → 0
pos → 1
"""

array(['neg', 'pos'], dtype=object)

## Train-Test-Split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [19]:
x_train.head()

       aa_000  ab_000        ac_000  ad_000  ...   ee_008  ee_009  ef_000  eg_000
39839   30606     NaN  3.260000e+02   226.0  ...  60828.0     0.0     0.0     0.0
57649     314     0.0  1.400000e+01    14.0  ...      2.0     0.0     0.0     0.0
11862    3572     NaN  0.000000e+00     NaN  ...      0.0     0.0     0.0     0.0
9381    33020     NaN  2.130706e+09    88.0  ...   2992.0     0.0     0.0     0.0
43612    2518     NaN  5.000000e+01    34.0  ...     88.0     0.0     0.0     0.0

[5 rows x 170 columns]

In [21]:
y_train

array([0, 0, 0, ..., 0, 0, 0], shape=(48000,))

In [22]:
print("X_train:", x_train.shape)
print("X_test:", x_test.shape)

print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (48000, 170)
X_test: (12000, 170)
y_train: (48000,)
y_test: (12000,)