##### Import Libraries

In [1]:
import pandas as pd
import numpy as np

##### Load Processed Train and Test Data

In [2]:
train_df=pd.read_csv("../data/processed/train.csv")

In [3]:
test_df=pd.read_csv("../data/processed/test.csv")

In [4]:
train_df.shape

(119400, 171)

In [5]:
test_df.shape

(27330, 171)

In [6]:
train_df.head()

,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000,class
0,-0.211517,-6.672382e-17,-0.461639,-0.005405,-0.042858,-0.053164,-0.01138,-0.022936,-0.055919,-0.111097,...,-0.380645,-0.370954,-0.345227,-0.303347,-0.194706,-0.294093,-0.169739,-0.021052,-0.021654,0
1,0.418794,-6.672382e-17,-0.461629,-0.005406,-0.042858,-0.053164,-0.01138,-0.022936,-0.055919,-0.111097,...,-0.382866,-0.372814,-0.347240,-0.306253,-0.201108,-0.294093,-0.169739,-0.021052,-0.021654,1
2,-0.210834,-6.672382e-17,2.293749,-0.005406,-0.042858,-0.053164,-0.01138,-0.022936,-0.055919,-0.111097,...,-0.379318,-0.362382,-0.332806,-0.304399,-0.201089,-0.294047,-0.169739,-0.021052,-0.021654,0
3,-0.033686,-4.370160e-01,-0.461639,-0.005396,-0.042858,-0.053164,-0.01138,-0.022936,-0.055919,-0.096702,...,-0.113349,-0.167131,-0.001989,0.646840,-0.151789,-0.289069,-0.169739,-0.021052,-0.021654,0
4,-0.208206,-6.672382e-17,-0.461639,-0.005404,-0.042858,-0.053164,-0.01138,-0.022936,-0.055919,-0.111097,...,-0.375156,-0.361848,-0.307624,-0.305537,-0.201100,-0.294093,-0.169739,-0.021052,-0.021654,0

In [7]:
test_df.head()

,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000,class
0,-0.101763,-6.672382e-17,2.293749,-0.005367,-0.042858,-0.053164,-1.010922e-02,-0.022717,-5.585031e-02,-0.111006,...,-0.209908,-2.380616e-01,-2.505123e-01,-0.209612,-0.146392,6.058065e-01,1.232924,-0.021052,-0.021654,NaN
1,-0.213510,-6.672382e-17,-0.461639,-0.005406,-0.042858,-0.053164,-1.137989e-02,-0.022936,-5.591883e-02,-0.111097,...,-0.382841,-3.727268e-01,-3.472398e-01,-0.306253,-0.201108,-2.940930e-01,-0.169739,-0.021052,-0.021654,NaN
2,-0.209098,-4.370160e-01,2.293749,-0.005405,-0.042858,-0.053164,-1.137989e-02,-0.022936,-5.591883e-02,-0.111097,...,-0.378423,-3.652879e-01,-3.340260e-01,-0.290212,-0.197353,-2.930830e-01,-0.169053,-0.021052,-0.021654,NaN
3,0.748620,-4.370160e-01,-0.461639,-0.005406,1.516210,4.596903,-1.389017e-18,0.000000,-1.038652e-17,0.000000,...,0.000000,-4.813233e-17,5.066850e-17,0.000000,0.000000,-6.123344e-17,0.000000,-0.021052,-0.021654,0.0
4,-0.196079,-6.672382e-17,2.293749,-0.005404,-0.042858,-0.053164,-1.137989e-02,-0.022936,-5.591883e-02,-0.111097,...,-0.342113,-3.349718e-01,-3.180161e-01,-0.282347,-0.186412,-2.447634e-01,-0.140365,-0.021052,-0.021654,NaN

##### Separate Features and Target

In [8]:
x_train=train_df.drop(columns=["class"])
y_train=train_df["class"]

In [9]:
x_test = test_df.drop(columns=["class"])
y_test = test_df["class"]

In [10]:
x_train.shape

(119400, 170)

In [11]:
x_test.shape

(27330, 170)

In [12]:
y_train.shape

(119400,)

In [13]:
y_test.shape

(27330,)